repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  revapi_diff: org.realityforge.revapi.diff:revapi-diff:jar:all:0.08
